my_string = input('Введите любой текст: ')
print('Количество символов в вашем тексте:', len(my_string))
print('Верхний регистр:', my_string.upper())
print('Нижний регистр:', my_string.lower())
print('Без пробелов:', my_string.replace(' ',''))
print('Первый символ:', my_string[0])
print('Последний символ:', my_string[-1])